dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  kovan:
    price_feed_address: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    # verify: True
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork:
    price_feed_address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}